version: '3'
services:
  db:
    image: postgres:9.4-alpine
    volumes:
      -  ./var/lib/postgresql/mydata
    expose:
      - '5432'
    environment:
      - POSTGRES_PASSWORD=password
      
  web:
    image: niki2401/data_stream_analytics
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp:Z
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_PASSWORD=password
    depends_on:
      - db
