# These config values will be shared by all environments but can be overridden.
common: &common
  client_id: "myapp"

development:
  <<: *common
  brokers:
    - 192.168.0.22:9092

test:
  <<: *common
  brokers:
    - 192.168.0.22:9092

production:
  <<: *common
  brokers:
    - 192.168.0.22:9092

